### ISSUE TITLE
Instance for `Functor` and `(->)`

### ISSUE THREAD

**Issue by guibou** [Soostone/string-conv#2]
I'm experimenting with instances of `StringConv` like:

``` haskell
instance (StringConv c a, StringConv b d) => StringConv (a -> b) (c -> d) where
  strConv _ fa = \x -> toS (fa (toS x))

instance (Functor f, StringConv a b) => StringConv (f a) (f b) where
  strConv _ = fmap toS
```

This allows to build higher level function using `toS`. For example `toS getArgs :: IO [Text]` and `toS System.FilePath.addExtension :: Text -> Text -> Text`. More generally, it can replace a painful call such as `toS <$> f (toS a) (toS b) (toS c)` to `(toS f) a b c`.

I think that the `(a -> b)` and `Functor` instances are enough for most use cases. However is this an overkill feature for minor convenience ?

**Comment by guibou** [comment]
Actually this may be more respectful of the `Leniency`:

``` haskell
instance (StringConv c a, StringConv b d) => StringConv (a -> b) (c -> d) where
  strConv leniency fa = \x -> strConv leniency (fa (strConv leniency x))

instance (Functor f, StringConv a b) => StringConv (f a) (f b) where
  strConv leniency = fmap (strConv leniency)
```

**Comment by MichaelXavier** [comment]
My first impression here is that it feels too abstract. The implicit convention of `StringConv` is that the type in the `b` position of `StringConv a b` be one of the common string-like types, and as such the library is providing a way to import one function that can convert between string representations rather than importing `Data.ByteString.Char8`, `Data.Text.Encoding`, etc etc.

With this addition, I suppose you'd get `StringConv [String] [Text]` for example, but `[Text]` isn't really a string-like type and I don't see how that's an improvement over calling `toS <$> strings`. At best these seem like they wouldn't be used 99% of the time, and when they are used the user would probably have to view the source to figure out what the instances actually do.

**Comment by guibou** [comment]
You are right ;)
